AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.11
    CodeUri: .
    Timeout: 60
    MemorySize: 128

Resources:

  ClassificationLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: classification-lambda
      Handler: src.lambda_handlers.classification_handler.classification_handler
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        DynamoDBStream:
          Type: DynamoDB
          Properties:
            Stream: arn:aws:dynamodb:us-east-1:102882775486:table/clearpath-alert-data/stream/2026-03-23T09:21:48.213
            StartingPosition: LATEST
            BatchSize: 10
            Enabled: true

  TwitterCollectionLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: twitter-collection-lambda
      Handler: src.lambda_handlers.twitter_collection_handler.twitter_collection_handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonSSMReadOnlyAccess
      Environment:
        Variables:
          TWITTER_API_KEY: "{{resolve:ssm:/clearpath/twitter-api-key}}"


  TwitterCollectionIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !ImportValue clearpath-api-id
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt TwitterCollectionLambda.Arn
      PayloadFormatVersion: "2.0"

  TwitterCollectionRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !ImportValue clearpath-api-id
      RouteKey: "GET /alert/collection"
      Target: !Sub integrations/${TwitterCollectionIntegration}

  TwitterCollectionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt TwitterCollectionLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub
        - "arn:aws:execute-api:us-east-1:102882775486:${ApiId}/*/*/alert/collection"
        - ApiId: !ImportValue clearpath-api-id
