repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
        args: ["--line-length=79"]

  - repo: local
    hooks:
      - id: line-limit
        name: Limit commit to 200 lines
        entry: util/pre-commit.sh --ignore-deps
        language: script
        always_run: true
