repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
        args: ["--line-length=79"]

  - repo: local
    hooks:
    - id: line-limit
      name: Limit commit to 200 lines
      entry: bash util/pre-commit.sh --ignore-deps
      language: system
      always_run: true
