AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - prod
  ApiId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /clearpath/staging/api-id

Mappings:
  EnvConfig:
    staging:
      BucketName: clearpath-weather-index-v1-staging
      TableName: clearpath-weather-data-staging
    prod:
      BucketName: clearpath-weather-index-v1-prod
      TableName: clearpath-weather-data

Globals:
  Function:
    Runtime: python3.11
    CodeUri: .
    Timeout: 30
    MemorySize: 128
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        S3_BUCKET_NAME: !FindInMap [EnvConfig, !Ref Environment, BucketName]
        WEATHER_TABLE_NAME: !FindInMap [EnvConfig, !Ref Environment, TableName]

Resources:

  WeatherBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !FindInMap [EnvConfig, !Ref Environment, BucketName]

  CollectionLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "collection-lambda-${Environment}"
      Handler: src.lambda_handlers.collection_lambda_handler.collection_lambda_handler
      Policies:
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref WeatherBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: weather_collected/

  RawLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "raw-lambda-${Environment}"
      Handler: src.lambda_handlers.raw_lambda_handler.raw_lambda_handler
      Policies:
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref WeatherBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: weather_raw/

  WeatherLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "weather-lambda-${Environment}"
      Handler: src.lambda_handlers.weather_lambda_handler.weather_lambda_handler
      Policies:
        - AmazonDynamoDBFullAccess

  ADAGELambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "adage-lambda-${Environment}"
      Handler: src.lambda_handlers.ADAGE_lambda_handler.ADAGE_lambda_handler
      Policies:
        - AmazonS3FullAccess

  WeatherIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ApiId
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt WeatherLambda.Arn
      PayloadFormatVersion: "2.0"

  WeatherRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiId
      RouteKey: "GET /weather/preprocessed"
      Target: !Sub "integrations/${WeatherIntegration}"

  WeatherPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt WeatherLambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:us-east-1:102882775486:${ApiId}/*/*/weather/preprocessed"

  ADAGEIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ApiId
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt ADAGELambda.Arn
      PayloadFormatVersion: "2.0"

  ADAGERoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ApiId
      RouteKey: "GET /weather/collection"
      Target: !Sub "integrations/${ADAGEIntegration}"

  ADAGEPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ADAGELambda.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:us-east-1:102882775486:${ApiId}/*/*/weather/collection"

Outputs:
  WeatherPreprocessedEndpoint:
    Description: Weather preprocessed endpoint
    Value: !Sub "https://${ApiId}.execute-api.${AWS::Region}.amazonaws.com/weather/preprocessed"
  WeatherADAGEEndpoint:
    Description: Weather ADAGE endpoint
    Value: !Sub "https://${ApiId}.execute-api.${AWS::Region}.amazonaws.com/weather/collection"
