name: Transport CI

on:
  pull_request:
    branches:
      - "main"
      - "develop/transport-microservice"
    paths:
      - "transport-microservice/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r transport-microservice/requirements.txt
          pip install -r requirements-dev.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 1. LINTING + FORMATTING CHECK
      - name: Run Ruff
        run: |
          ruff format --check transport-microservice/
          ruff check transport-microservice/

      # 2. UNIT TESTING
      - name: Run unit tests
        run: pytest transport-microservice/tests/unit/

      # 3. INTEGRATION TESTING
      - name: Run integration tests
        env:
          GOOGLE_WEATHER_API_KEY: ${{ secrets.GOOGLE_WEATHER_API_KEY }}
        run: pytest transport-microservice/tests/integration/

      # 4. COVERAGE TESTING
      - name: Run coverage
        run: |
          coverage run -m pytest transport-microservice/tests/
          coverage report
          coverage xml -o transport-microservice/coverage.xml
          coverage html -d transport-microservice/htmlcov

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: transport-testing-report
          path: |
            transport-microservice/htmlcov/
            transport-microservice/coverage.xml
